apiVersion: apps/v1
kind: Deployment
metadata:
  name: juridico-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: juridico-api
  template:
    metadata:
      labels:
        app: juridico-api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: juridico-api
          image: pesdro/juridicoapi:{{tag}}
          ports:
            - containerPort: 8501
          envFrom:
            - configMapRef:
                name: juridicoapi-env
---
apiVersion: v1
kind: Service
metadata:
  name: juridico-api
spec:
  type: NodePort
  selector:
    app: juridico-api
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 32767
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: linux-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: juridico-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70