apiVersion: apps/v1
kind: Deployment
metadata:
  name: juridico-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: juridico-api
  template:
    metadata:
      labels:
        app: juridico-api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: juridico-api
        image: pesdro/juridicoapi{{tag}}
        ports:
        - containerPort: 8501
		    envFrom:
        - configMapRef:
            name: juridicoapi-env
---
apiVersion: v1
kind: Service
metadata:
  name: juridico-api
spec:
  type: NodePort
  selector:
    app: juridico-api
  ports:
    - port: 8501          # porta do Service
      targetPort: 8501   # porta do container
      nodePort: 38501    # porta exposta no node
